### PR TITLE
Update form.yml.erb - add facet2 impact bmad sim

### PR DESCRIPTION
**Pull request by sanjeev-one**
This script runs a container which has a conda env setup with impact t and bmad. The container contains jupyter notebook files as examples and the facet 2 lattice. These get copied to a users chosen directory.

### CODE REVIEW

**Comment by pav511** [comment]
Hi @sanjeev-one, can you open up an additional PR to s3df-dev branch? We can merge it there for testing.

**Comment by sanjeev-one** [comment]
if it works it should create a directory with jupyter notebook files and the impact / bmad sim should run

**Comment by pav511** [comment]
Hi @sanjeev-one the changes are in dev. The directories are created and the sim appears to be running. Can you verify expected behavior at s3df-dev.slac.stanford.edu/ondemand?
Also one addition to the PR is that '- facet2' option should be added under 'options:' on line 103 of form.yml.erb to populate the image dropdown option.

**Comment by sanjeev-one** [comment]
Looks to be working.  Thank you for the help. 

Were you able to do:
 '- facet2' option should be added under 'options:' on line 103 of form.yml.erb to populate the image dropdown option.

or is it something I need to do?

**Comment by sanjeev-one** [comment]
Do you have an estimate for when this will be in production?

**Comment by pav511** [comment]
Hi @sanjeev-one this has been merged to prod

**Pull request merged**
